using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cards;

public class CardsDatabase : MonoBehaviour
{
    public static List<CardTemplate> cardList = new List<CardTemplate>();

    void Awake()
    {
        cardList.Add(new CardTemplate(1, "Królewski łowca głów", " ", 3, 4, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/KingsHunter")));        
        cardList.Add(new CardTemplate(2, "Spaczony władca", " ", 4, 3, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NECROMANCER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/CorruptedRuler")));
        cardList.Add(new CardTemplate(3, "Mag królewskiej straży", "Kiedy wchodzi na pole bitwy zadaje 2 punkty obrażeń wszystkim jednostka przeciwnika.", 3, 3, 6, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_PERCING_ATACK, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/Mage1")));
        cardList.Add(new CardTemplate(4, "Sześcioręki wojownik", " ", 5, 6, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/6HandedWarrior")));
        cardList.Add(new CardTemplate(5, "Rycerz śmierci", " ", 3, 4, 6, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NECROMANCER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/DeathKnight")));
        cardList.Add(new CardTemplate(6, "Bard", "Wszyscy ludzie pod twoją kontrolą otrzymują +1/+1.", 2, 2, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/HumanBard")));
        cardList.Add(new CardTemplate(7, "Leśny druid", "Przywraca wszystkie przyjazne jednostki do maksymalnego stanu zdrowia.", 2, 2, 6, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/HumanDruid")));
        cardList.Add(new CardTemplate(8, "Leśny łowca", " ", 2, 3, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/Hunter")));
        cardList.Add(new CardTemplate(9, "Opiekunka armii", " ", 1, 4, 2, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_DEFENDER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/HumanDefender")));
        cardList.Add(new CardTemplate(10, "Wszechwiedzący kleryk", " ", 3, 6, 6, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/PowerfulCleric")));
        cardList.Add(new CardTemplate(11, "Niedoświadczona czarodziejka", "Po wejściu na pole bitwy zadaje 2 punkty obrażeń losowej jednostce przeciwnika.", 2, 2, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/Mage2")));
        cardList.Add(new CardTemplate(12, "Łotrzyk", " ", 1, 1, 1, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/Rouge")));
        cardList.Add(new CardTemplate(13, "Leśny mnich", " ", 1, 5, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_DEFENDER, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/ForestMonk")));
        cardList.Add(new CardTemplate(14, "Poszukiwacz wiedzy", "Kiedy wchodzi na pole bitwy dobierz kartę. ", 2, 2, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/KnowlageSeeker")));
        cardList.Add(new CardTemplate(15, "Poszukiwacz szkarbów", "Kiedy wchodzi na pole bitwy dobierz kartę. ", 4, 3, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_BRAWLER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/TreasureSearcher")));
        cardList.Add(new CardTemplate(16, "Najemnik", " ", 4, 3, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/Tenant")));
        cardList.Add(new CardTemplate(17, "Dowódcznyni floty", " ", 3, 4, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/HumanSailer")));
        cardList.Add(new CardTemplate(18, "Poszukiwaczka artefaktów", "Zniszcz artefakt przeciwnika.", 2, 2, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/ArtifactSeeker")));
        cardList.Add(new CardTemplate(19, "Zbiegły mag", "Zniszcz losową przyjazną jednostkę i zadaj obrażenia graczowi równe jej punktą ataku.", 5, 4, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/RougeMage")));
        cardList.Add(new CardTemplate(20, "Arcykapłanka", " ", 4, 5, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_PERCING_ATACK, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/HumanPriest")));
        cardList.Add(new CardTemplate(21, "Omamiony walką wojownik", " ", 5, 5, 7, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_PERCING_ATACK, CardKeywords.KEYWORD_BRAWLER, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/Berserker")));
        cardList.Add(new CardTemplate(22, "Świeżo upieczona rekrutka", " ", 2, 2, 2, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_HUMAN, CardKeywords.KEYWORD_BRAWLER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Humans/HumanRecruit")));

        cardList.Add(new CardTemplate(23, "Władczyni many", "Po wprowadzeniu na pole gry gracz dostaje dodatkowy punkt many.", 1, 1, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ManaWelder")));
        cardList.Add(new CardTemplate(24, "Elfi rekrut", " ", 2, 2, 2, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfRecruit")));
        cardList.Add(new CardTemplate(25, "Elficki jeźdzca", " ", 3, 4, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfRaider")));
        cardList.Add(new CardTemplate(26, "Niedoświadczona łowczyni", " ", 3, 4, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenHunter")));
        cardList.Add(new CardTemplate(27, "Wędrowny bard", "Wszystkie elfy pod twoją kontrolą otrzymują +1/+1.", 3, 2, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenBard")));
        cardList.Add(new CardTemplate(28, "Spaczony elf", " ", 4, 3, 6, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NECROMANCER, CardKeywords.KEYWORD_BRAWLER, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/CorruptedElf")));
        cardList.Add(new CardTemplate(29, "Elficka wróżka", " ", 4, 4, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenFairy")));
        cardList.Add(new CardTemplate(30, "Elficki wojownik", " ", 3, 4, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenWarrior")));
        cardList.Add(new CardTemplate(31, "Elfia kapłanka lasu", "Kiedy zostaje wprowadzona do gry dodaje graczowi 5 punktów zdrowia.", 4, 3, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenPriest")));
        cardList.Add(new CardTemplate(32, "Tajemnicza czarodzejka", "Po wprowadzeniu na pole bitwy niszczy losową kartę w polu przeciwnika.", 2, 2, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenMage")));
        cardList.Add(new CardTemplate(33, "Dowódca bojówki elfów", " ", 6, 5, 7, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_BRAWLER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ComandoLeader")));
        cardList.Add(new CardTemplate(34, "Majtek", " ", 1, 2, 1, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenSailor")));
        cardList.Add(new CardTemplate(35, "Zdrajca komanda", "Kiedy zostaje wprowadzony na pole gry niszczy przyjazną jednostkę i leczy przeciwnika za wartość jej ataku.", 6, 5, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenTraitor")));
        cardList.Add(new CardTemplate(36, "Elficki druid", "Kiedy zostaje wprowadzony do gry dodaje graczowi 3 punktów zdrowia.", 3, 4, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenDruid")));
        cardList.Add(new CardTemplate(37, "Nieumarły elf", " ", 3, 3, 5, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NECROMANCER, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenUndead")));
        cardList.Add(new CardTemplate(38, "Elficki mag bojowy", "Po wejściu na pole bitwy zadaje 3 punkty obrażeń losowej jednostce przeciwnika.", 3, 3, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenMage2")));
        cardList.Add(new CardTemplate(39, "Elficki strzelec", " ", 2, 3, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_ARCHER, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenArcher")));
        cardList.Add(new CardTemplate(40, "Adeptka magii", "Kiedy wchodzi na pole bitwy dobierz kartę.", 3, 2, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenMagicAdept")));
        cardList.Add(new CardTemplate(41, "Elficka kapłanka światła", " ", 3, 2, 4, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_FLYING, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenCleric")));
        cardList.Add(new CardTemplate(42, "Zagubiony elf", "Kiedy wchodzi na pole bitwy dobierz kartę. ", 2, 2, 3, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/LostElf")));
        cardList.Add(new CardTemplate(43, "Elfi mędrzec", "Zniszcz artefakt przeciwnika.", 4, 4, 6, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/ElfenSage")));
        cardList.Add(new CardTemplate(44, "Łowca ludzi", "Po wprowadzeniu na pole bitwy niszczy losową kartę w polu przeciwnika. ", 4, 4, 7, CardType.CARDTYPE_MONSTER, CardClass.CARDCLASS_ELF, CardKeywords.KEYWORD_CLERIC, CardKeywords.KEYWORD_BRAWLER, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Elfs/HunterOfHumans")));


        cardList.Add(new CardTemplate(45, "Kula ognia", "Zadaj stworowi przeciwnika 3 punkty obrażeń.", 0, 0, 2, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/FireBall")));
        cardList.Add(new CardTemplate(46, "Deszcz Meteorytów", "Zadaj wszystkich stworą przeciwnika 4 punkty obrażeń", 0, 0, 4, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/MeteorRain")));
        cardList.Add(new CardTemplate(47, "Lodowe pociski", "Zadaj wszystkich stworą przeciwnika 2 punkty obrażeń", 0, 0, 1, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/IceMissiles")));
        cardList.Add(new CardTemplate(48, "Starożytna wiedza", "Dobierz dwie karty z talii.", 0, 0, 1, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/OldWisdom")));
        cardList.Add(new CardTemplate(49, "Kataklizm", "Zniszcz wszystkie jednostki na polu bitwy.", 0, 0, 7, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/DestroyAll")));
        cardList.Add(new CardTemplate(50, "Latające noże", "Zadaj przeciwnikowi 3 punktów obrażeń.", 0, 0, 1, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/FlyingKnives")));
        cardList.Add(new CardTemplate(51, "Ognisty podmuch", "Zadaj przeciwnikowi 5 punktów obrażeń.", 0, 0, 3, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/FireBlast")));
        cardList.Add(new CardTemplate(52, "Wysysanie życia", "Zadaj jednostce 4 punktów obrażeń i ulecz się o 4 punkty zdrowia.", 0, 0, 3, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/HealthDrain")));
        cardList.Add(new CardTemplate(53, "Uzdrowienie", "Ulecz się o 4 punkty zdrowia.", 0, 0, 1, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/Heal")));
        cardList.Add(new CardTemplate(54, "Śmiertelna kołysanka", "Zniszcz wrogiego stwora.", 0, 0, 4, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/DeadlyLullaby")));
        cardList.Add(new CardTemplate(55, "Zniszczenie artefaktu", "Zniszcz artefakt.", 0, 0, 4, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/ArtifactDestroyer")));
        cardList.Add(new CardTemplate(56, "Odrodzenie stworów", "Przywróć potwora z cmentarzyska do swojej ręki.", 0, 0, 1, CardType.CARDTYPE_SPELL, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/Spells/MonsterReborn")));


        cardList.Add(new CardTemplate(57, "Naszyjnik życia", "Z początkiem tury wszystkie stwory pod twoją kontrolą otrzymują +1 do punktów życia.", 0, 0, 2, CardType.CARDTYPE_ARTIFACT, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/CrystalOfLife")));
        cardList.Add(new CardTemplate(58, "Kryształ many", "Kiedy znajduję się na polu gry pod twoją kontrolą, otrzymujesz dodatkowy punkt many na początku tury.", 0, 0, 2, CardType.CARDTYPE_ARTIFACT, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/ManaCrystal")));
        cardList.Add(new CardTemplate(59, "Serce elfów", "Kiedy znajduje się na polu gry wszystkie elfy pod twoją kontrolą dostają +1/+2.", 0, 0, 3, CardType.CARDTYPE_ARTIFACT, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/HearthOfElfs")));
        cardList.Add(new CardTemplate(60, "Legendarny krasnoludzki róg", "Z początkiem tury wszystkie stwory pod twoją kontrolą otrzymują +2 do punktów ataku.", 0, 0, 3, CardType.CARDTYPE_ARTIFACT, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/DwarfsHorn")));
        cardList.Add(new CardTemplate(61, "Księga śmierci", "Wszystkie stwory przeciwnika na początku tury dostają -2 do punktów życia. Jeżeli życie stwora spadnie do 0 trafia on na cmentarzysko.", 0, 0, 4, CardType.CARDTYPE_ARTIFACT, CardClass.CARDCLASS_NEUTRAL, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, CardKeywords.KEYWORD_NONE, Resources.Load<Sprite>("CardFaces/BookOfDeath")));
    }
}
